export const ACTION_SHOW_ALERT = 'ACTION_SHOW_ALERT';

export const AUTH_APPLY_ACCESS_TOKEN = 'AUTH_APPLY_ACCESS_TOKEN';

export const AUTH_SIGN_IN_REQUEST = 'AUTH_SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'AUTH_SIGN_IN_FAILURE';

export const TEAMS_GET_LIST_REQUEST = 'TEAMS_GET_LIST_REQUEST';
export const TEAMS_GET_LIST_SUCCESS = 'TEAMS_GET_LIST_SUCCESS';
export const TEAMS_GET_LIST_FAILURE = 'TEAMS_GET_LIST_FAILURE';